# Generated by Django 5.2.3 on 2025-06-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='ano_publicacao',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='editora',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='isbn',
            field=models.CharField(default=1234567, max_length=13, unique=True, verbose_name='ISBN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, verbose_name='Estoque'),
        ),
    ]
