# Generated by Django 5.2.3 on 2025-08-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0001_initial'),
        ('categoria', '0001_initial'),
        ('livro', '0002_livro_ano_publicacao_livro_editora_livro_isbn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='categoria',
        ),
        migrations.AddField(
            model_name='livro',
            name='autor',
            field=models.ManyToManyField(blank=True, to='autor.autor'),
        ),
        migrations.AddField(
            model_name='livro',
            name='categoria',
            field=models.ManyToManyField(blank=True, to='categoria.categoria'),
        ),
    ]
