# Generated by Django 5.2.3 on 2025-06-25 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('detail_usuario', 'Pode ver o detalhe de usuário')]},
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios_usuarios',
        ),
    ]
