# Generated by Django 5.2.3 on 2025-08-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_options_alter_usuario_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='endereco',
        ),
        migrations.AddField(
            model_name='usuario',
            name='bairro',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='cidade',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='rua',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
