# Generated by Django 5.2.3 on 2025-08-26 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0001_initial'),
        ('usuario', '0002_alter_usuario_options_alter_usuario_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='administrador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprestimos_feitos', to='usuario.usuario'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='data_prevista_devolucao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('andamento', 'Em andamento'), ('atrasado', 'Atrasado'), ('devolvido', 'Devolvido')], default='andamento', max_length=20),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprestimos_recebidos', to='usuario.usuario'),
        ),
    ]
