# Generated by Django 5.2.3 on 2025-06-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nacionalidade', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Autor_autores',
                'permissions': [('detail_autor', 'Pode ver o detalhe de autor')],
            },
        ),
    ]
